// Pixel-Symbole für die Oberfläche, als Zeichenketten gemalt.
// Jedes Symbol: Legende (Zeichen -> Palettenfarbe) und Zeilen.

import { P, hexToCss } from '../render/palette.js';

const ICONS = {
  holz: {
    legend: { k: P.e1, b: P.e3, r: P.e6, R: P.e7, c: P.e8 },
    rows: [
      '...kkkk...',
      '.kkbbbbkk.',
      '.kbrrrrbk.',
      'kbrRRRRrbk',
      'kbrRccRrbk',
      'kbrRccRrbk',
      'kbrRRRRrbk',
      '.kbrrrrbk.',
      '.kkbbbbkk.',
      '...kkkk...',
    ],
  },
  stein: {
    legend: { k: P.s1, S: P.s6, s: P.s8, D: P.s4 },
    rows: [
      '..........',
      '....kkk...',
      '..kkSSSk..',
      '.kSSsSSSk.',
      '.kSsSSSSSk',
      'kSSSSSSDSk',
      'kSSSSSDDSk',
      'kDSSSDDDDk',
      '.kDDDDDDk.',
      '..kkkkkk..',
    ],
  },
  fasern: {
    legend: { g: P.g7, G: P.g5, t: P.e8, k: P.g2 },
    rows: [
      '.g..g..g..',
      '.g.g.g.g..',
      '..g.g.gg..',
      '..gGgGgg..',
      '..GgGgGG..',
      '..tttttt..',
      '..GgGgGG..',
      '..gGgGgg..',
      '..GGkGGk..',
      '..........',
    ],
  },
  schrott: {
    legend: { k: P.s2, S: P.s6, o: P.s8, r: P.r3 },
    rows: [
      '..........',
      '.kkkkkkkk.',
      '.kSSSSSSk.',
      '.kSoSSoSk.',
      '.kSSrrSSk.',
      '.kSSrSSSk.',
      '.kSoSSoSk.',
      '.kSSSSSSk.',
      '.kkkkkkkk.',
      '..........',
    ],
  },
  zahnraeder: {
    legend: { k: P.e2, G: P.f5, g: P.f7 },
    rows: [
      '....kk....',
      '.kk.GG.kk.',
      '.kGGgGGGk.',
      '..GGkkGG..',
      'kGGk..kGGk',
      'kGgk..kGGk',
      '..GGkkGG..',
      '.kGGGGGGk.',
      '.kk.GG.kk.',
      '....kk....',
    ],
  },
  moderkerne: {
    legend: { k: P.d0, M: P.a2, m: P.a3, L: P.a6, W: P.a4 },
    rows: [
      '..........',
      '...kkkk...',
      '..kMMmMk..',
      '.kMmLLMMk.',
      '.kMLWLLMk.',
      '.kMLLLLMk.',
      '.kMMLLMMk.',
      '..kMMMMk..',
      '...kkkk...',
      '..........',
    ],
  },
  stoff: {
    legend: { k: P.b0, A: P.b3, B: P.b2, a: P.a4 },
    rows: [
      '..........',
      '.kkkkkkkk.',
      '.kAAAAAAk.',
      '.kAaAAaAk.',
      '.kAAAAAAk.',
      '.kBBBBBBk.',
      '.kAAAAAAk.',
      '.kAaAAaAk.',
      '.kkkkkkkk.',
      '..........',
    ],
  },
  axt: {
    legend: { S: P.s6, W: P.s8, h: P.e5, H: P.e3 },
    rows: [
      '............',
      '..SS........',
      '.SSSS.......',
      'SWSSSh......',
      'SWSSShH.....',
      '.SSS.hH.....',
      '......hH....',
      '.......hH...',
      '........hH..',
      '.........hH.',
      '..........H.',
      '............',
    ],
  },
  schaufel: {
    legend: { S: P.s6, W: P.s8, h: P.e5, H: P.e3 },
    rows: [
      '.........HH.',
      '.........hH.',
      '........hH..',
      '.......hH...',
      '......hH....',
      '.....hH.....',
      '..SSSH......',
      '.SWSSS......',
      '.SWSSS......',
      '.SSSS.......',
      '..SS........',
      '............',
    ],
  },
  pfanne: {
    legend: { k: P.n1, K: P.s2, w: P.s4, h: P.e3 },
    rows: [
      '..kkkk......',
      '.kKKKKk.....',
      'kKwKKKKk....',
      'kKKKKKKk....',
      'kKKKKKKk....',
      '.kKKKKkhh...',
      '..kkkk..hh..',
      '.........hh.',
      '..........h.',
      '............',
    ],
  },
  rechen: {
    legend: { S: P.s5, h: P.e5, H: P.e3 },
    rows: [
      'S.S.S.S.....',
      'SSSSSSS.....',
      '...hH.......',
      '....hH......',
      '.....hH.....',
      '......hH....',
      '.......hH...',
      '........hH..',
      '.........hH.',
      '..........H.',
    ],
  },
  faeustlinge: {
    legend: { r: P.f2, R: P.f3, w: P.s9, k: P.r1 },
    rows: [
      '..kkk.....',
      '.kRRRk.kk.',
      '.kRrRkkRk.',
      '.kRRRRRRk.',
      '.kRrRRrRk.',
      '.kRRRRRk..',
      '.kwwwwwk..',
      '..kkkkk...',
    ],
  },
  schild: {
    legend: { k: P.e1, w: P.e5, W: P.e7, m: P.s6 },
    rows: [
      '.kkkkkkk.',
      'kwWwWwWwk',
      'kWmmmmmWk',
      'kwmWwWmwk',
      'kWmwWwmWk',
      '.kwmmmwk.',
      '..kwWwk..',
      '...kwk...',
      '....k....',
    ],
  },
  spitzhacke: {
    legend: { S: P.s5, k: P.s2, h: P.e5, H: P.e3 },
    rows: [
      '............',
      '.kSSSSSSSSk.',
      'kS...hH...Sk',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '......H.....',
      '............',
    ],
  },
  werkbank: {
    legend: { k: P.e1, T: P.e4, h: P.e5, s: P.s6, W: P.e6, V: P.s4, L: P.e3, P: P.e8 },
    rows: [
      '................',
      '..kkkkkkk.......',
      '..kTTTTTk.......',
      '..kThTsTk.......',
      '..kThTsTk.......',
      '..kTTTTTk.......',
      'kkkkkkkkkkkkkkkk',
      'kWWWWWWWWWWWWVVk',
      'kkkkkkkkkkkkkkkk',
      '.kL..........Lk.',
      '.kL.PPPPPP...Lk.',
      '.kL.kkkkkk...Lk.',
      '.kL..........Lk.',
      '.kL..........Lk.',
      '.kk..........kk.',
      '................',
    ],
  },
  barrikade: {
    legend: { k: P.e1, W: P.e6, B: P.e4 },
    rows: [
      '................',
      '..W....W....W...',
      '.kWk..kWk..kWk..',
      '.kWk..kWk..kWk..',
      '.kWk..kWk..kWk..',
      'kkkkkkkkkkkkkkk.',
      'kBBBBBBBBBBBBBk.',
      'kkkkkkkkkkkkkkk.',
      '.kWk..kWk..kWk..',
      '.kWk..kWk..kWk..',
      'kkkkkkkkkkkkkkk.',
      'kBBBBBBBBBBBBBk.',
      'kkkkkkkkkkkkkkk.',
      '.kWk..kWk..kWk..',
      '.kkk..kkk..kkk..',
      '................',
    ],
  },
  laternenpfahl: {
    legend: { k: P.e1, P: P.e3, S: P.s4, Y: P.f6, W: P.f8 },
    rows: [
      '................',
      '....kkkkkkk.....',
      '....kPPPPPk.....',
      '....kP..kkkk....',
      '....kP..kSSk....',
      '....kP.kYYYYk...',
      '....kP.kYWWYk...',
      '....kP.kYYYYk...',
      '....kP..kSSk....',
      '....kP..........',
      '....kP..........',
      '....kP..........',
      '....kP..........',
      '...kkPPk........',
      '..kSSSSSk.......',
      '................',
    ],
  },
  beet: {
    legend: { k: P.e1, g: P.g7, G: P.g5, E: P.e3, d: P.e2, B: P.e4 },
    rows: [
      '................',
      '................',
      '................',
      '....g..g..g.....',
      '...gGg.gG.gGg...',
      '....G..G...G....',
      'kkkkkkkkkkkkkkkk',
      'kBEEEEEEEEEEEEBk',
      'kBEdEEdEEdEEEEBk',
      'kBBBBBBBBBBBBBBk',
      'kkkkkkkkkkkkkkkk',
      '................',
    ],
  },
  bank: {
    legend: { k: P.e1, B: P.e4, S: P.e6, L: P.e3 },
    rows: [
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kBBBBBBBBBBk..',
      '..kkkkkkkkkkkk..',
      '..kL........Lk..',
      '.kkkkkkkkkkkkkk.',
      '.kSSSSSSSSSSSSk.',
      '.kkkkkkkkkkkkkk.',
      '..kL........Lk..',
      '..kL........Lk..',
      '..kk........kk..',
      '................',
    ],
  },
  huette: {
    legend: { k: P.e1, R: P.r3, W: P.e6, Y: P.f6, D: P.e3 },
    rows: [
      '......kk....k...',
      '.....kRRk..kYk..',
      '....kRRRRkkYYYk.',
      '...kRRRRRRkkYk..',
      '..kRRRRRRRRkYk..',
      '...kWWWWWWkkYk..',
      '...kYYWkDWk.kk..',
      '...kYYWkDWk.....',
      '...kWWWkDWk.....',
      '...kkkkkkkk.....',
    ],
  },

  zelt: {
    legend: { k: P.e1, C: P.e8, c: P.e7, R: P.r3, D: P.e2, Y: P.f6 },
    rows: [
      '.......kk.......',
      '......kCCk......',
      '.....kCCCck.....',
      '....kCCCCCck....',
      '...kRRRDRRRRk...',
      '..kRRRDYDRRRRk..',
      '..kCCcDYDcCCCk..',
      '.kCCCDDYDDCCCck.',
      '.kCCDDDDDDDCCck.',
      'kkkkkkkkkkkkkkkk',
    ],
  },
  moebel: {
    legend: { k: P.e1, Y: P.f6, y: P.f5, S: P.s3, R: P.r3, r: P.r2, W: P.a4 },
    rows: [
      '..kkkkkk........',
      '.kYYYYYYk.......',
      'kYYyyyyYYk......',
      '.kkkkkkkk.......',
      '....kSk....kkkk.',
      '....kSk...kRRRRk',
      '....kSk...kRWWRk',
      '....kSk..kRRRRRk',
      '....kSk..krRRRrk',
      '...kSSSk.kr...rk',
      '..kkkkkkkkk...kk',
    ],
  },
  funkturm: {
    legend: { k: P.s1, S: P.s5, s: P.s4, Y: P.f6, y: P.f7, R: P.r3 },
    rows: [
      '.....kYk......',
      '....kyYyk.....',
      '.....kSk......',
      '....kSsSk.....',
      '....kSkSk.....',
      '...kSsksSk....',
      '...kSk.kSk....',
      '..kSsk.ksSk...',
      '..kSk...kSk...',
      '.kSsk...ksSk..',
      '.kkkk...kkkk..',
    ],
  },
  koerbchen: {
    legend: { k: P.e1, B: P.e6, b: P.e5, W: P.a4, U: P.b3 },
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kBbBbBbBbBbBbk.',
      '.kbWUWUWUWUWUBk.',
      '.kBUWUWUWUWUWbk.',
      '.kbBbBbBbBbBbBk.',
      '..kkkkkkkkkkkk..',
    ],
  },
  pfote: {
    legend: { k: P.e1, B: P.e6 },
    rows: [
      '.kk..kk.',
      'kBBkkBBk',
      '.kk..kk.',
      '..kkkk..',
      '.kBBBBk.',
      'kBBBBBBk',
      '.kkkkkk.',
    ],
  },
  abriss: {
    legend: { r: P.r4, k: P.r1 },
    rows: [
      '.kk.......kk.',
      'krrk.....krrk',
      '.krrk...krrk.',
      '..krrk.krrk..',
      '...krrkrrk...',
      '....krrrk....',
      '...krrkrrk...',
      '..krrk.krrk..',
      '.krrk...krrk.',
      'krrk.....krrk',
      '.kk.......kk.',
    ],
  },
  mini_holz: { legend: { a: P.e6, b: P.e4 }, rows: ['.aa.', 'abba', 'abba', '.aa.'] },
  mini_stein: { legend: { a: P.s7, b: P.s5 }, rows: ['.ab.', 'abbb', 'bbbb', '.bb.'] },
  mini_fasern: { legend: { a: P.g7, b: P.g5 }, rows: ['a.a.', '.a.a', 'bbbb', 'b.b.'] },
  mini_stoff: { legend: { a: P.b4, b: P.b3 }, rows: ['aaaa', 'abab', 'aaaa', 'bbbb'] },
  mini_schrott: { legend: { a: P.s8, b: P.s6, r: P.r3 }, rows: ['abba', 'brbb', 'bbrb', 'abba'] },
  mini_zahnraeder: { legend: { a: P.f6, b: P.f4 }, rows: ['a.a.', '.bb.', '.bb.', 'a..a'] },
  mini_moderkerne: { legend: { a: P.a3, b: P.a2, c: P.a6 }, rows: ['.ab.', 'acca', 'bccb', '.bb.'] },
  laterne: {
    legend: { k: P.s1, M: P.s5, y: P.f5, Y: P.f6, W: P.f8 },
    rows: [
      '....kkkk....',
      '...k....k...',
      '....kkkk....',
      '..kkkkkkkk..',
      '..kMMMMMMk..',
      '..kyYYYYyk..',
      '..kYYWWYYk..',
      '..kYWWWWYk..',
      '..kYYWWYYk..',
      '..kyYYYYyk..',
      '..kMMMMMMk..',
      '..kkkkkkkk..',
      '...kkkkkk...',
    ],
  },
  laterneAus: {
    legend: { k: P.s1, M: P.s5, g: P.n6, G: P.n7, W: P.s8 },
    rows: [
      '....kkkk....',
      '...k....k...',
      '....kkkk....',
      '..kkkkkkkk..',
      '..kMMMMMMk..',
      '..kgGGGGgk..',
      '..kGGWGGGk..',
      '..kGWGGGGk..',
      '..kGGGGGGk..',
      '..kgGGGGgk..',
      '..kMMMMMMk..',
      '..kkkkkkkk..',
      '...kkkkkk...',
    ],
  },
  bolzen: {
    legend: { t: P.s8, s: P.s6, d: P.e3, r: P.e9, w: P.e5 },
    rows: [
      '.....tt.....',
      '.....ss.....',
      '.d...ss...d.',
      '.dd..ss..dd.',
      '..ddrssrdd..',
      '...rrssrr...',
      '.....ww.....',
      '.....ww.....',
      '.....ww.....',
      '....wwww....',
      '....wddw....',
      '.....dd.....',
    ],
  },
  katapult: {
    legend: { g: P.g5, o: P.f4, O: P.f5, d: P.e3, w: P.e5, s: P.s5 },
    rows: [
      '.......g....',
      '.....oooo...',
      '....oOoOoo..',
      '....ooooOo..',
      '.....oooo...',
      '....dwwwwd..',
      '.....w......',
      '....w.......',
      '...w........',
      '..w.........',
      '.ssss.......',
      '.s..s.......',
    ],
  },
  sprenger: {
    legend: { c: P.b5, y: P.f5, b: P.b2, B: P.b3 },
    rows: [
      '.c...c...c..',
      '..c..c..c...',
      '...c.c.c....',
      '....yyy.....',
      '.....y......',
      '...bbbbb....',
      '..bBBBBBb...',
      '..bBbbbBb...',
      '..bBBBBBb...',
      '..bBbbbBb...',
      '..bBBBBBb...',
      '...bbbbb....',
    ],
  },
  laternenturm: {
    legend: { k: P.s2, Y: P.f6, W: P.f8, e: P.e4, s: P.s5 },
    rows: [
      '....kkkk....',
      '...kYYYYk...',
      '...kYWWYk...',
      '...kYWWYk...',
      '...kYYYYk...',
      '....kkkk....',
      '.....ee.....',
      '.....ee.....',
      '.....ee.....',
      '.....ee.....',
      '...ssssss...',
      '..ssssssss..',
    ],
  },
  magnet: {
    legend: { r: P.r3, R: P.r4, w: P.a4 },
    rows: [
      '..ww....ww..',
      '..ww....ww..',
      '..rR....rR..',
      '..rR....rR..',
      '..rR....rR..',
      '..rRr..rRR..',
      '...rRRRRR...',
      '....rrrr....',
    ],
  },
  herz: {
    legend: { r: P.r2, R: P.a0, W: P.a1 },
    rows: [
      '.rr...rr.',
      'rRRr.rRRr',
      'rRWRrRRRr',
      'rRRRRRRRr',
      '.rRRRRRr.',
      '..rRRRr..',
      '...rRr...',
      '....r....',
    ],
  },
  faust: {
    legend: { k: P.h0, h: P.h3, H: P.h2, b: P.g5 },
    rows: [
      '..kkkkk..',
      '.khkhkhk.',
      '.khkhkhk.',
      '.kkkkkkkk',
      '.khhhhhk.',
      '.khHHHhk.',
      '..kkkkk..',
      '..bbbbb..',
      '..bbbbb..',
    ],
  },
  stiefel: {
    legend: { b: P.e2, B: P.e4, w: P.a4 },
    rows: [
      '....bbb.....',
      '....bBb.....',
      '....bBb..w..',
      '....bBb.ww..',
      '....bBbwww..',
      '..bbbBbbb...',
      '.bBBBBBBb...',
      '.bbbbbbbb...',
    ],
  },
  reparieren: {
    legend: { s: P.s4, S: P.s6, w: P.e5 },
    rows: [
      '..ssss......',
      '.sSSSSs.....',
      '..ssssS.....',
      '.....Sw.....',
      '......ww....',
      '.......ww...',
      '........ww..',
      '.........ww.',
    ],
  },
  warnung: {
    legend: { r: P.r2, Y: P.f6, k: P.n0 },
    rows: [
      '.....r.....',
      '....rYr....',
      '....rYr....',
      '...rYkYr...',
      '...rYkYr...',
      '..rYYkYYr..',
      '..rYYYYYr..',
      '.rYYYkYYYr.',
      '.rrrrrrrrr.',
    ],
  },
  schaedel: {
    legend: { w: P.s8, W: P.s9, k: P.n0, g: P.g5 },
    rows: [
      '..wwwww..',
      '.wWWWWWw.',
      'wWkkWkkWw',
      'wWkkWkkWw',
      'wWWWkWWWw',
      '.wWWWWWw.',
      '..wkwkw..',
      '..g...g..',
    ],
  },
  ziel: {
    legend: { k: P.e2, s: P.e5, r: P.r3, R: P.r4, w: P.a4 },
    rows: [
      '.k.......',
      '.sRRRRr..',
      '.sRRwRRr.',
      '.sRwwwRr.',
      '.sRRwRRr.',
      '.sRRRRr..',
      '.s.......',
      '.s.......',
      '.s.......',
      'kkk......',
    ],
  },
  sonne: {
    legend: { y: P.f5, Y: P.f6, W: P.f8 },
    rows: [
      '.....y......',
      '.y...y...y..',
      '..y.....y...',
      '....YYY.....',
      '...YWWWY....',
      'yy.YWWWY.yy.',
      '...YWWWY....',
      '....YYY.....',
      '..y.....y...',
      '.y...y...y..',
      '.....y......',
      '............',
    ],
  },
  mond: {
    legend: { L: P.n8, M: P.n7, s: P.f7 },
    rows: [
      '............',
      '....LLL...s.',
      '..LLMM.....s',
      '..LMM.....s.',
      '.LMM........',
      '.LMM........',
      '.LMM........',
      '.LMMM.....L.',
      '..LMMMM..LL.',
      '..LLMMMMLL..',
      '....LLLL....',
      '............',
    ],
  },
  daemmerung: {
    legend: { y: P.f5, Y: P.f6, W: P.f8, h: P.d4 },
    rows: [
      '............',
      '............',
      '.....y......',
      '..y.....y...',
      '............',
      '....YYY.....',
      '...YWWWY....',
      '..YWWWWWY...',
      'hhhhhhhhhhhh',
      '..h..h..h...',
      '............',
      '............',
    ],
  },
  haus: {
    legend: { k: P.e1, R: P.r3, W: P.e6, Y: P.f6, D: P.e3 },
    rows: [
      '....kk....',
      '...kRRk...',
      '..kRRRRk..',
      '.kRRRRRRk.',
      'kRRRRRRRRk',
      '.kWWWWWWk.',
      '.kYYWkDWk.',
      '.kYYWkDWk.',
      '.kWWWkDWk.',
      '.kkkkkkkk.',
    ],
  },
  weiter: {
    legend: { c: P.e9 },
    rows: ['ccccc', '.ccc.', '..c..'],
  },
  zeiger: {
    legend: { c: P.f6 },
    rows: ['c...', 'cc..', 'ccc.', 'cc..', 'c...'],
  },
};

const cache = new Map();

function build(name) {
  const icon = ICONS[name];
  if (!icon) throw new Error(`Unbekanntes Symbol: ${name}`);
  const h = icon.rows.length;
  const w = Math.max(...icon.rows.map((r) => r.length));
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');
  icon.rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const hex = icon.legend[row[x]];
      if (hex === undefined) continue;
      ctx.fillStyle = hexToCss(hex);
      ctx.fillRect(x, y, 1, 1);
    }
  });
  return canvas;
}

export function iconCanvas(name) {
  if (!cache.has(name)) cache.set(name, build(name));
  return cache.get(name);
}

export function drawIcon(ctx, name, x, y) {
  const c = iconCanvas(name);
  ctx.drawImage(c, Math.round(x), Math.round(y));
  return c;
}

export function iconSize(name) {
  const c = iconCanvas(name);
  return { w: c.width, h: c.height };
}
