// Pixel-Symbole für die Oberfläche, als Zeichenketten gemalt.
// Jedes Symbol: Legende (Zeichen -> Palettenfarbe) und Zeilen.

import { P, hexToCss } from '../render/palette.js';

const ICONS = {
  holz: {
    legend: { k: P.e1, b: P.e3, r: P.e6, R: P.e7, c: P.e8 },
    rows: [
      '...kkkk...',
      '.kkbbbbkk.',
      '.kbrrrrbk.',
      'kbrRRRRrbk',
      'kbrRccRrbk',
      'kbrRccRrbk',
      'kbrRRRRrbk',
      '.kbrrrrbk.',
      '.kkbbbbkk.',
      '...kkkk...',
    ],
  },
  stein: {
    legend: { k: P.s1, S: P.s6, s: P.s8, D: P.s4 },
    rows: [
      '..........',
      '....kkk...',
      '..kkSSSk..',
      '.kSSsSSSk.',
      '.kSsSSSSSk',
      'kSSSSSSDSk',
      'kSSSSSDDSk',
      'kDSSSDDDDk',
      '.kDDDDDDk.',
      '..kkkkkk..',
    ],
  },
  fasern: {
    legend: { g: P.g7, G: P.g5, t: P.e8, k: P.g2 },
    rows: [
      '.g..g..g..',
      '.g.g.g.g..',
      '..g.g.gg..',
      '..gGgGgg..',
      '..GgGgGG..',
      '..tttttt..',
      '..GgGgGG..',
      '..gGgGgg..',
      '..GGkGGk..',
      '..........',
    ],
  },
  schrott: {
    legend: { k: P.s2, S: P.s6, o: P.s8, r: P.r3 },
    rows: [
      '..........',
      '.kkkkkkkk.',
      '.kSSSSSSk.',
      '.kSoSSoSk.',
      '.kSSrrSSk.',
      '.kSSrSSSk.',
      '.kSoSSoSk.',
      '.kSSSSSSk.',
      '.kkkkkkkk.',
      '..........',
    ],
  },
  teile: {
    legend: { k: P.t1, T: P.t4, t: P.t3, g: P.g5, s: P.b2 },
    rows: [
      '..k.k.k...',
      '.kTkTkTk..',
      '.kTkTkTk..',
      '.kTTTTTkk.',
      '.kTgTTTTTk',
      '.kTggTTtk.',
      '.ktTTTTtk.',
      '..kssssk..',
      '..kssssk..',
      '...kkkk...',
    ],
  },
  zahnraeder: {
    legend: { k: P.e2, G: P.f5, g: P.f7 },
    rows: [
      '....kk....',
      '.kk.GG.kk.',
      '.kGGgGGGk.',
      '..GGkkGG..',
      'kGGk..kGGk',
      'kGgk..kGGk',
      '..GGkkGG..',
      '.kGGGGGGk.',
      '.kk.GG.kk.',
      '....kk....',
    ],
  },
  moderkerne: {
    legend: { k: P.d0, M: P.a2, m: P.a3, L: P.a6, W: P.a4 },
    rows: [
      '..........',
      '...kkkk...',
      '..kMMmMk..',
      '.kMmLLMMk.',
      '.kMLWLLMk.',
      '.kMLLLLMk.',
      '.kMMLLMMk.',
      '..kMMMMk..',
      '...kkkk...',
      '..........',
    ],
  },
  stoff: {
    legend: { k: P.b0, A: P.b3, B: P.b2, a: P.a4 },
    rows: [
      '..........',
      '.kkkkkkkk.',
      '.kAAAAAAk.',
      '.kAaAAaAk.',
      '.kAAAAAAk.',
      '.kBBBBBBk.',
      '.kAAAAAAk.',
      '.kAaAAaAk.',
      '.kkkkkkkk.',
      '..........',
    ],
  },
  axt: {
    legend: { S: P.s6, W: P.s8, h: P.e5, H: P.e3 },
    rows: [
      '............',
      '..SS........',
      '.SSSS.......',
      'SWSSSh......',
      'SWSSShH.....',
      '.SSS.hH.....',
      '......hH....',
      '.......hH...',
      '........hH..',
      '.........hH.',
      '..........H.',
      '............',
    ],
  },
  schaufel: {
    legend: { S: P.s6, W: P.s8, h: P.e5, H: P.e3 },
    rows: [
      '.........HH.',
      '.........hH.',
      '........hH..',
      '.......hH...',
      '......hH....',
      '.....hH.....',
      '..SSSH......',
      '.SWSSS......',
      '.SWSSS......',
      '.SSSS.......',
      '..SS........',
      '............',
    ],
  },
  pfanne: {
    legend: { k: P.n1, K: P.s2, w: P.s4, h: P.e3 },
    rows: [
      '..kkkk......',
      '.kKKKKk.....',
      'kKwKKKKk....',
      'kKKKKKKk....',
      'kKKKKKKk....',
      '.kKKKKkhh...',
      '..kkkk..hh..',
      '.........hh.',
      '..........h.',
      '............',
    ],
  },
  rechen: {
    legend: { S: P.s5, h: P.e5, H: P.e3 },
    rows: [
      'S.S.S.S.....',
      'SSSSSSS.....',
      '...hH.......',
      '....hH......',
      '.....hH.....',
      '......hH....',
      '.......hH...',
      '........hH..',
      '.........hH.',
      '..........H.',
    ],
  },
  faeustlinge: {
    legend: { r: P.f2, R: P.f3, w: P.s9, k: P.r1 },
    rows: [
      '..kkk.....',
      '.kRRRk.kk.',
      '.kRrRkkRk.',
      '.kRRRRRRk.',
      '.kRrRRrRk.',
      '.kRRRRRk..',
      '.kwwwwwk..',
      '..kkkkk...',
    ],
  },
  schild: {
    legend: { k: P.e1, w: P.e5, W: P.e7, m: P.s6 },
    rows: [
      '.kkkkkkk.',
      'kwWwWwWwk',
      'kWmmmmmWk',
      'kwmWwWmwk',
      'kWmwWwmWk',
      '.kwmmmwk.',
      '..kwWwk..',
      '...kwk...',
      '....k....',
    ],
  },
  spitzhacke: {
    legend: { S: P.s5, k: P.s2, h: P.e5, H: P.e3 },
    rows: [
      '............',
      '.kSSSSSSSSk.',
      'kS...hH...Sk',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '.....hH.....',
      '......H.....',
      '............',
    ],
  },
  werkbank: {
    legend: { k: P.e1, T: P.e4, h: P.e5, s: P.s6, W: P.e6, V: P.s4, L: P.e3, P: P.e8 },
    rows: [
      '................',
      '..kkkkkkk.......',
      '..kTTTTTk.......',
      '..kThTsTk.......',
      '..kThTsTk.......',
      '..kTTTTTk.......',
      'kkkkkkkkkkkkkkkk',
      'kWWWWWWWWWWWWVVk',
      'kkkkkkkkkkkkkkkk',
      '.kL..........Lk.',
      '.kL.PPPPPP...Lk.',
      '.kL.kkkkkk...Lk.',
      '.kL..........Lk.',
      '.kL..........Lk.',
      '.kk..........kk.',
      '................',
    ],
  },
  // M9.1: Spanischer Reiter – zwei Kreuze aus angespitzten Pfählen, ein Balken quer hindurch
  barrikade: {
    legend: { k: P.e1, T: P.e8, W: P.e6, w: P.e5, B: P.e4 },
    rows: [
      'kk....kkkk....kk',
      'TTk..kTTTTk..kTT',
      'kWwkkWwkkWwkkWwk',
      'kWwkkWwkkWwkkWwk',
      '.kWwWwk..kWwWwk.',
      '.kWwWwk..kWwWwk.',
      'kkkkkkkkkkkkkkkk',
      'kBBBBBBBBBBBBBBk',
      'kkkkkkkkkkkkkkkk',
      '.kWwWwk..kWwWwk.',
      '.kWwWwk..kWwWwk.',
      'kWwkkWwkkWwkkWwk',
      'kWwkkWwkkWwkkWwk',
      'TTk..kTTTTk..kTT',
      'kk....kkkk....kk',
    ],
  },
  laternenpfahl: {
    legend: { k: P.e1, P: P.e3, S: P.s4, Y: P.f6, W: P.f8 },
    rows: [
      '................',
      '....kkkkkkk.....',
      '....kPPPPPk.....',
      '....kP..kkkk....',
      '....kP..kSSk....',
      '....kP.kYYYYk...',
      '....kP.kYWWYk...',
      '....kP.kYYYYk...',
      '....kP..kSSk....',
      '....kP..........',
      '....kP..........',
      '....kP..........',
      '....kP..........',
      '...kkPPk........',
      '..kSSSSSk.......',
      '................',
    ],
  },
  beet: {
    legend: { k: P.e1, g: P.g7, G: P.g5, E: P.e3, d: P.e2, B: P.e4 },
    rows: [
      '................',
      '................',
      '................',
      '....g..g..g.....',
      '...gGg.gG.gGg...',
      '....G..G...G....',
      'kkkkkkkkkkkkkkkk',
      'kBEEEEEEEEEEEEBk',
      'kBEdEEdEEdEEEEBk',
      'kBBBBBBBBBBBBBBk',
      'kkkkkkkkkkkkkkkk',
      '................',
    ],
  },
  holzlager: {
    legend: { k: P.e1, R: P.e5, r: P.e4, L: P.e8, l: P.e6 },
    rows: [
      '................',
      '...kkkkkkkkkk...',
      '..kRRRRRRRRRRk..',
      '.kRrRRRrRRRrRRk.',
      '.kkkkkkkkkkkkkk.',
      '.kkkkkkkkkkkkk..',
      '.kLlkLlkLlkLlk..',
      '.kllkllkllkllk..',
      '.kkkkkkkkkkkkkk.',
      '..kLlkLlkLlkLlk.',
      '..kllkllkllkllk.',
      '.kkkkkkkkkkkkkk.',
      '.kLlkLlkLlkLlk..',
      '.kllkllkllkllk..',
      '.kkkkkkkkkkkkk..',
      '................',
    ],
  },
  bank: {
    legend: { k: P.e1, B: P.e4, S: P.e6, L: P.e3 },
    rows: [
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kBBBBBBBBBBk..',
      '..kkkkkkkkkkkk..',
      '..kL........Lk..',
      '.kkkkkkkkkkkkkk.',
      '.kSSSSSSSSSSSSk.',
      '.kkkkkkkkkkkkkk.',
      '..kL........Lk..',
      '..kL........Lk..',
      '..kk........kk..',
      '................',
    ],
  },
  huette: {
    legend: { k: P.e1, R: P.r3, W: P.e6, Y: P.f6, D: P.e3 },
    rows: [
      '......kk....k...',
      '.....kRRk..kYk..',
      '....kRRRRkkYYYk.',
      '...kRRRRRRkkYk..',
      '..kRRRRRRRRkYk..',
      '...kWWWWWWkkYk..',
      '...kYYWkDWk.kk..',
      '...kYYWkDWk.....',
      '...kWWWkDWk.....',
      '...kkkkkkkk.....',
    ],
  },

  zelt: {
    legend: { k: P.e1, C: P.e8, c: P.e7, R: P.r3, D: P.e2, Y: P.f6 },
    rows: [
      '.......kk.......',
      '......kCCk......',
      '.....kCCCck.....',
      '....kCCCCCck....',
      '...kRRRDRRRRk...',
      '..kRRRDYDRRRRk..',
      '..kCCcDYDcCCCk..',
      '.kCCCDDYDDCCCck.',
      '.kCCDDDDDDDCCck.',
      'kkkkkkkkkkkkkkkk',
    ],
  },
  moebel: {
    legend: { k: P.e1, Y: P.f6, y: P.f5, S: P.s3, R: P.r3, r: P.r2, W: P.a4 },
    rows: [
      '..kkkkkk........',
      '.kYYYYYYk.......',
      'kYYyyyyYYk......',
      '.kkkkkkkk.......',
      '....kSk....kkkk.',
      '....kSk...kRRRRk',
      '....kSk...kRWWRk',
      '....kSk..kRRRRRk',
      '....kSk..krRRRrk',
      '...kSSSk.kr...rk',
      '..kkkkkkkkk...kk',
    ],
  },
  funkturm: {
    legend: { k: P.s1, S: P.s5, s: P.s4, Y: P.f6, y: P.f7, R: P.r3 },
    rows: [
      '.....kYk......',
      '....kyYyk.....',
      '.....kSk......',
      '....kSsSk.....',
      '....kSkSk.....',
      '...kSsksSk....',
      '...kSk.kSk....',
      '..kSsk.ksSk...',
      '..kSk...kSk...',
      '.kSsk...ksSk..',
      '.kkkk...kkkk..',
    ],
  },
  koerbchen: {
    legend: { k: P.e1, B: P.e6, b: P.e5, W: P.a4, U: P.b3 },
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kBbBbBbBbBbBbk.',
      '.kbWUWUWUWUWUBk.',
      '.kBUWUWUWUWUWbk.',
      '.kbBbBbBbBbBbBk.',
      '..kkkkkkkkkkkk..',
    ],
  },
  pfote: {
    legend: { k: P.e1, B: P.e6 },
    rows: [
      '.kk..kk.',
      'kBBkkBBk',
      '.kk..kk.',
      '..kkkk..',
      '.kBBBBk.',
      'kBBBBBBk',
      '.kkkkkk.',
    ],
  },
  abriss: {
    legend: { r: P.r4, k: P.r1 },
    rows: [
      '.kk.......kk.',
      'krrk.....krrk',
      '.krrk...krrk.',
      '..krrk.krrk..',
      '...krrkrrk...',
      '....krrrk....',
      '...krrkrrk...',
      '..krrk.krrk..',
      '.krrk...krrk.',
      'krrk.....krrk',
      '.kk.......kk.',
    ],
  },
  mini_holz: { legend: { a: P.e6, b: P.e4 }, rows: ['.aa.', 'abba', 'abba', '.aa.'] },
  mini_stein: { legend: { a: P.s7, b: P.s5 }, rows: ['.ab.', 'abbb', 'bbbb', '.bb.'] },
  mini_fasern: { legend: { a: P.g7, b: P.g5 }, rows: ['a.a.', '.a.a', 'bbbb', 'b.b.'] },
  mini_stoff: { legend: { a: P.b4, b: P.b3 }, rows: ['aaaa', 'abab', 'aaaa', 'bbbb'] },
  mini_schrott: { legend: { a: P.s8, b: P.s6, r: P.r3 }, rows: ['abba', 'brbb', 'bbrb', 'abba'] },
  mini_zahnraeder: { legend: { a: P.f6, b: P.f4 }, rows: ['a.a.', '.bb.', '.bb.', 'a..a'] },
  mini_moderkerne: { legend: { a: P.a3, b: P.a2, c: P.a6 }, rows: ['.ab.', 'acca', 'bccb', '.bb.'] },
  laterne: {
    legend: { k: P.s1, M: P.s5, y: P.f5, Y: P.f6, W: P.f8 },
    rows: [
      '....kkkk....',
      '...k....k...',
      '....kkkk....',
      '..kkkkkkkk..',
      '..kMMMMMMk..',
      '..kyYYYYyk..',
      '..kYYWWYYk..',
      '..kYWWWWYk..',
      '..kYYWWYYk..',
      '..kyYYYYyk..',
      '..kMMMMMMk..',
      '..kkkkkkkk..',
      '...kkkkkk...',
    ],
  },
  laterneAus: {
    legend: { k: P.s1, M: P.s5, g: P.n6, G: P.n7, W: P.s8 },
    rows: [
      '....kkkk....',
      '...k....k...',
      '....kkkk....',
      '..kkkkkkkk..',
      '..kMMMMMMk..',
      '..kgGGGGgk..',
      '..kGGWGGGk..',
      '..kGWGGGGk..',
      '..kGGGGGGk..',
      '..kgGGGGgk..',
      '..kMMMMMMk..',
      '..kkkkkkkk..',
      '...kkkkkk...',
    ],
  },
  bolzen: {
    legend: { t: P.s8, s: P.s6, d: P.e3, r: P.e9, w: P.e5 },
    rows: [
      '.....tt.....',
      '.....ss.....',
      '.d...ss...d.',
      '.dd..ss..dd.',
      '..ddrssrdd..',
      '...rrssrr...',
      '.....ww.....',
      '.....ww.....',
      '.....ww.....',
      '....wwww....',
      '....wddw....',
      '.....dd.....',
    ],
  },
  katapult: {
    legend: { g: P.g5, o: P.f4, O: P.f5, d: P.e3, w: P.e5, s: P.s5 },
    rows: [
      '.......g....',
      '.....oooo...',
      '....oOoOoo..',
      '....ooooOo..',
      '.....oooo...',
      '....dwwwwd..',
      '.....w......',
      '....w.......',
      '...w........',
      '..w.........',
      '.ssss.......',
      '.s..s.......',
    ],
  },
  sprenger: {
    legend: { c: P.b5, y: P.f5, b: P.b2, B: P.b3 },
    rows: [
      '.c...c...c..',
      '..c..c..c...',
      '...c.c.c....',
      '....yyy.....',
      '.....y......',
      '...bbbbb....',
      '..bBBBBBb...',
      '..bBbbbBb...',
      '..bBBBBBb...',
      '..bBbbbBb...',
      '..bBBBBBb...',
      '...bbbbb....',
    ],
  },
  laternenturm: {
    legend: { k: P.s2, Y: P.f6, W: P.f8, e: P.e4, s: P.s5 },
    rows: [
      '....kkkk....',
      '...kYYYYk...',
      '...kYWWYk...',
      '...kYWWYk...',
      '...kYYYYk...',
      '....kkkk....',
      '.....ee.....',
      '.....ee.....',
      '.....ee.....',
      '.....ee.....',
      '...ssssss...',
      '..ssssssss..',
    ],
  },
  magnet: {
    legend: { r: P.r3, R: P.r4, w: P.a4 },
    rows: [
      '..ww....ww..',
      '..ww....ww..',
      '..rR....rR..',
      '..rR....rR..',
      '..rR....rR..',
      '..rRr..rRR..',
      '...rRRRRR...',
      '....rrrr....',
    ],
  },
  herz: {
    legend: { r: P.r2, R: P.a0, W: P.a1 },
    rows: [
      '.rr...rr.',
      'rRRr.rRRr',
      'rRWRrRRRr',
      'rRRRRRRRr',
      '.rRRRRRr.',
      '..rRRRr..',
      '...rRr...',
      '....r....',
    ],
  },
  faust: {
    legend: { k: P.h0, h: P.h3, H: P.h2, b: P.g5 },
    rows: [
      '..kkkkk..',
      '.khkhkhk.',
      '.khkhkhk.',
      '.kkkkkkkk',
      '.khhhhhk.',
      '.khHHHhk.',
      '..kkkkk..',
      '..bbbbb..',
      '..bbbbb..',
    ],
  },
  stiefel: {
    legend: { b: P.e2, B: P.e4, w: P.a4 },
    rows: [
      '....bbb.....',
      '....bBb.....',
      '....bBb..w..',
      '....bBb.ww..',
      '....bBbwww..',
      '..bbbBbbb...',
      '.bBBBBBBb...',
      '.bbbbbbbb...',
    ],
  },
  reparieren: {
    legend: { s: P.s4, S: P.s6, w: P.e5 },
    rows: [
      '..ssss......',
      '.sSSSSs.....',
      '..ssssS.....',
      '.....Sw.....',
      '......ww....',
      '.......ww...',
      '........ww..',
      '.........ww.',
    ],
  },
  warnung: {
    legend: { r: P.r2, Y: P.f6, k: P.n0 },
    rows: [
      '.....r.....',
      '....rYr....',
      '....rYr....',
      '...rYkYr...',
      '...rYkYr...',
      '..rYYkYYr..',
      '..rYYYYYr..',
      '.rYYYkYYYr.',
      '.rrrrrrrrr.',
    ],
  },
  schaedel: {
    legend: { w: P.s8, W: P.s9, k: P.n0, g: P.g5 },
    rows: [
      '..wwwww..',
      '.wWWWWWw.',
      'wWkkWkkWw',
      'wWkkWkkWw',
      'wWWWkWWWw',
      '.wWWWWWw.',
      '..wkwkw..',
      '..g...g..',
    ],
  },
  ziel: {
    legend: { k: P.e2, s: P.e5, r: P.r3, R: P.r4, w: P.a4 },
    rows: [
      '.k.......',
      '.sRRRRr..',
      '.sRRwRRr.',
      '.sRwwwRr.',
      '.sRRwRRr.',
      '.sRRRRr..',
      '.s.......',
      '.s.......',
      '.s.......',
      'kkk......',
    ],
  },
  sonne: {
    legend: { y: P.f5, Y: P.f6, W: P.f8 },
    rows: [
      '.....y......',
      '.y...y...y..',
      '..y.....y...',
      '....YYY.....',
      '...YWWWY....',
      'yy.YWWWY.yy.',
      '...YWWWY....',
      '....YYY.....',
      '..y.....y...',
      '.y...y...y..',
      '.....y......',
      '............',
    ],
  },
  mond: {
    legend: { L: P.n8, M: P.n7, s: P.f7 },
    rows: [
      '............',
      '....LLL...s.',
      '..LLMM.....s',
      '..LMM.....s.',
      '.LMM........',
      '.LMM........',
      '.LMM........',
      '.LMMM.....L.',
      '..LMMMM..LL.',
      '..LLMMMMLL..',
      '....LLLL....',
      '............',
    ],
  },
  daemmerung: {
    legend: { y: P.f5, Y: P.f6, W: P.f8, h: P.d4 },
    rows: [
      '............',
      '............',
      '.....y......',
      '..y.....y...',
      '............',
      '....YYY.....',
      '...YWWWY....',
      '..YWWWWWY...',
      'hhhhhhhhhhhh',
      '..h..h..h...',
      '............',
      '............',
    ],
  },
  // Wetter in der Uhr (M12)
  regen: {
    legend: { W: P.s9, L: P.s7, M: P.s6, b: P.b4 },
    rows: [
      '............',
      '....LLL.....',
      '..LLWWWL....',
      '.LWWWWWWLL..',
      'LWWWWWWWWWL.',
      'LMMMMMMMMML.',
      '.MMMMMMMMM..',
      '............',
      '..b...b...b.',
      '.b...b...b..',
      '............',
      '...b...b....',
    ],
  },
  nebel: {
    legend: { Y: P.f6, W: P.f8, L: P.s8, M: P.s6 },
    rows: [
      '............',
      '.....YYY....',
      '....YWWWY...',
      '...YWWWWWY..',
      '............',
      '.LLLLLLLLL..',
      '............',
      '..MMMMMMMMM.',
      '............',
      'LLLLLLLL....',
      '............',
      '...MMMMMMMM.',
    ],
  },
  wind: {
    legend: { L: P.s8, r: P.f4, R: P.r4 },
    rows: [
      '............',
      '.LLLLLLL....',
      '........L...',
      '.......L....',
      'LLLLLLL..rr.',
      '.........rR.',
      '.LLLLLLLLL..',
      '..........L.',
      '.........L..',
      '..LLLLLLL...',
      '............',
      '............',
    ],
  },
  haus: {
    legend: { k: P.e1, R: P.r3, W: P.e6, Y: P.f6, D: P.e3 },
    rows: [
      '....kk....',
      '...kRRk...',
      '..kRRRRk..',
      '.kRRRRRRk.',
      'kRRRRRRRRk',
      '.kWWWWWWk.',
      '.kYYWkDWk.',
      '.kYYWkDWk.',
      '.kWWWkDWk.',
      '.kkkkkkkk.',
    ],
  },
  // Besondere Turmteile (Meilenstein 10)
  fernrohr: {
    legend: { k: P.e1, B: P.f6, b: P.f5, d: P.f3, l: P.n2, g: P.b5, s: P.s4 },
    rows: [
      '.......kkkk',
      '......kgllk',
      '.....kBBBk.',
      '....kBBbk..',
      '...kdBbk...',
      '..kBBbk....',
      '.kBbbk.....',
      'kssk.......',
      'kkk........',
    ],
  },
  schmierfett: {
    legend: { k: P.e1, G: P.g5, g: P.g3, y: P.f6, s: P.s5, S: P.s6 },
    rows: [
      '....kk......',
      '...kssk.....',
      '..kkkkkk....',
      '.kGGGGGGk.kk',
      '.kGyyGGGkkSk',
      '.kGyyGGGSSk.',
      '.kGGGGGGkk..',
      '.kgGGGGGk...',
      '..kkkkkk....',
    ],
  },
  gluecksmuenze: {
    legend: { k: P.e1, r: P.r3, Y: P.f6, y: P.f8, d: P.f4 },
    rows: [
      '....r....',
      '....r....',
      '..kkkkk..',
      '.kYYYYYk.',
      'kYyYYYYYk',
      'kYYYdYYYk',
      'kYYYYYyYk',
      '.kYYYYYk.',
      '..kkkkk..',
    ],
  },
  // Balduins Boot (Zeile »Tschüss, Balduin!« im Handelsfenster)
  boot: {
    legend: { k: P.e1, r: P.r2, e: P.e6, n: P.n3, b: P.b2, s: P.s8 },
    rows: [
      '........kkkk..',
      '.......krrrrk.',
      '.......kenek..',
      '.......keeek..',
      'kkkkkkkkkkkkkk',
      'kbbbbbbbbbbbbk',
      '.kssssssssssk.',
      '..kbbbbbbbbk..',
      '...kkkkkkkk...',
    ],
  },
  weiter: {
    legend: { c: P.e9 },
    rows: ['ccccc', '.ccc.', '..c..'],
  },
  zeiger: {
    legend: { c: P.f6 },
    rows: ['c...', 'cc..', 'ccc.', 'cc..', 'c...'],
  },
  // Fähigkeiten (M16)
  blitz: {
    legend: { k: P.s1, M: P.s5, Y: P.f6, W: P.f8, r: P.f7 },
    rows: [
      'r....kk....r',
      '.r..k..k..r.',
      '...kkkkkk...',
      '...kMMMMk...',
      'rr.kYWWYk.rr',
      '...kWWWWk...',
      '...kYWWYk...',
      '...kMMMMk...',
      '.r..kkkk..r.',
      'r..........r',
    ],
  },
  wurf: {
    legend: { k: P.f0, O: P.f4, o: P.f3, g: P.g5, G: P.g3, l: P.s7 },
    rows: [
      '........g...',
      '.......gG...',
      '.....kkkkkk.',
      'll..kOoOOoOk',
      '...kOoOOoOOk',
      '.lllkOoOOoOk',
      '...kOoOOoOOk',
      'll..kOoOOoOk',
      '.....kkkkkk.',
    ],
  },
  pfiff: {
    legend: { k: P.e1, B: P.e6, a: P.f7 },
    rows: [
      '.........aa.',
      '.........a.a',
      '.kk..kk..a..',
      'kBBkkBBk.a..',
      '.kk..kk.aa..',
      '..kkkk..aa..',
      '.kBBBBk.....',
      'kBBBBBBk....',
      '.kkkkkk.....',
    ],
  },
  notbrett: {
    legend: { k: P.e1, b: P.e5, B: P.e7, s: P.s8 },
    rows: [
      '.kkk....kkk.',
      '.kbk....kbk.',
      '.kbk....kbk.',
      'kkkkkkkkkkkk',
      'kBsBBBBBBsBk',
      'kbbbbbbbbbbk',
      'kkkkkkkkkkkk',
      '.kbk....kbk.',
      '.kbk....kbk.',
      '.kkk....kkk.',
    ],
  },
  anfeuern: {
    legend: { k: P.e2, R: P.f3, r: P.f5, y: P.f7 },
    rows: [
      '.k.......y..',
      '.kRRR......y',
      '.kRrrRRR....',
      '.kRRRRRRRR..',
      '.kRrrRRR..y.',
      '.kRRR.......',
      '.k......y...',
      '.k..........',
      '.k..........',
      'kkk.........',
    ],
  },
  wirbel: {
    legend: { w: P.s9, W: P.s7, s: P.s6, e: P.e5 },
    rows: [
      '...wwwww....',
      '.ww.....ww..',
      'w.........w.',
      'w...ss....ww',
      'W..sss...www',
      'W....e......',
      'W....e....W.',
      '.W...e...W..',
      '..WW...WW...',
      '....WWW.....',
    ],
  },
  // Rechte Maustaste (Taste der ersten Fähigkeit)
  maus: {
    legend: { k: P.n0, W: P.s8, R: P.f6 },
    rows: [
      '.kkk.',
      'kWkRk',
      'kWkRk',
      'kkkkk',
      'kWWWk',
      'kWWWk',
      '.kkk.',
    ],
  },
  // Notizbuch (M18): aufgeschlagenes Buch mit Lesezeichen
  buch: {
    legend: { k: P.e1, p: P.e9, P: P.s9, l: P.s6, r: P.r3, b: P.e5 },
    rows: [
      '.......r...',
      '.kkkk.kkrk.',
      'kpppPkPppk.',
      'kplpPkPlpk.',
      'kpppPkPppk.',
      'kplpPkPlpk.',
      'kpppPkPppk.',
      'kbbbbkbbbbk',
      '.kkkkkkkkk.',
    ],
  },
  // Zubehör (M17e): Dornen, Pechkessel, Alarmglocke (die Laterne hat ihr Symbol schon)
  dornen: {
    legend: { k: P.s1, s: P.s5, S: P.s8, w: P.e5, W: P.e7 },
    rows: [
      '..S...S...S.',
      '.kSk.kSk.kSk',
      '.ksk.ksk.ksk',
      'kssskssskssk',
      'kWWWWWWWWWWk',
      'kwwwwwwwwwwk',
      'kkkkkkkkkkkk',
    ],
  },
  pech: {
    legend: { k: P.n0, s: P.s2, S: P.s4, n: P.n1, g: P.n6, f: P.f5, F: P.f7 },
    rows: [
      '...F..F...',
      '..fFf.f...',
      '.kkkkkkkk.',
      'kgnnnnnnnk',
      'kSkkkkkkSk',
      '.kssssssk.',
      '.kssssssk.',
      '..kssssk..',
      '.kk....kk.',
    ],
  },
  glocke: {
    legend: { k: P.e1, b: P.f3, B: P.f5, h: P.f7, s: P.s5 },
    rows: [
      '....kk....',
      '...kssk...',
      '...kBBk...',
      '..kBhBbk..',
      '..kBhBbk..',
      '.kBBhBBbk.',
      '.kBBBBBbk.',
      'kbbbbbbbbk',
      '.kkkkkkkk.',
      '....ss....',
    ],
  },
  // Wall und Tor (M17)
  wall: {
    legend: { k: P.e1, w: P.e6, W: P.e8, g: P.g4, G: P.g5, e: P.e3 },
    rows: [
      '.W..W..W..W.',
      'kwk.kwk.kwk.',
      'kwkkkwkkkwkk',
      'kwwwwwwwwwwk',
      'kwkkkwkkkwkk',
      'kwk.kwk.kwk.',
      'gGgggGgggGgg',
      'eggGgggGgggG',
      'eeeeeeeeeeee',
    ],
  },
  tor: {
    legend: { k: P.e1, w: P.e6, W: P.e8, s: P.s6, r: P.r3 },
    rows: [
      'rrr......rrr',
      'kWk......kWk',
      'kWkkkkkkkkWk',
      'kWkwwkkwwkWk',
      'kWkwwkkwwkWk',
      'kWkwsksswkWk',
      'kWkwwkkwwkWk',
      'kWkwwkkwwkWk',
      'kkkkkkkkkkkk',
    ],
  },
  // M19: Familien und Fallen aus den Bauplänen, der Bauplan selbst
  glockenturm: {
    legend: { k: P.e1, r: P.r2, R: P.r3, w: P.e5, y: P.f5, Y: P.f7, s: P.s5 },
    rows: [
      '.....kk.....',
      '....kRRk....',
      '...kRRRRk...',
      '..kRRrrRRk..',
      '.kkkkkkkkkk.',
      '..w..yy..w..',
      '..w.yYyy.w..',
      '..w.yyyy.w..',
      '..wyyyyyyw..',
      '..w..kk..w..',
      '.ssssssssss.',
      'ssssssssssss',
    ],
  },
  windrad: {
    legend: { c: P.s8, C: P.s9, e: P.e4, k: P.e2, p: P.e5 },
    rows: [
      'c.........CC',
      'cc.......CC.',
      '.cc.....CC..',
      '..ce...eC...',
      '...eekee....',
      '....kkk.....',
      '...eekee....',
      '..Ce.p.ec...',
      '.CC..p..cc..',
      'CC...p...cc.',
      '....ppp....c',
      '...ppppp....',
    ],
  },
  bienenkorb: {
    legend: { k: P.e2, s: P.e7, S: P.e8, d: P.e5, h: P.n0, y: P.f6, b: P.n1, e: P.e4 },
    rows: [
      '.........yb.',
      '....kkkk..y.',
      '...kSSSSk...',
      '..kssssssk..',
      '..kddddddk..',
      '.kssssssssk.',
      '.kddddddddk.',
      'kssssssssssk',
      'kdddhhhddddk',
      'kssshhhssssk',
      'kkkkkkkkkkkk',
      '.eeeeeeeeee.',
    ],
  },
  vogelscheuche: {
    legend: { h: P.e3, p: P.f4, P: P.f5, f: P.n1, w: P.e5, c: P.r3, C: P.r4, s: P.e7 },
    rows: [
      '....hhhh....',
      '...hhhhhh...',
      '....pPPp....',
      '....pffp....',
      '....pPPp....',
      's.wwwCCwww.s',
      '.sccCCCCccs.',
      '....cCCc....',
      '....cCCc....',
      '.....ww.....',
      '.....ww.....',
      '....wwww....',
    ],
  },
  stachelbrett: {
    legend: { k: P.e2, b: P.e5, B: P.e6, n: P.s7, N: P.s9 },
    rows: [
      '.N..N..N..N.',
      '.n..n..n..n.',
      '.n..n..n..n.',
      'kkkkkkkkkkkk',
      'kBBBBBBBBBBk',
      'kbbbbbbbbbbk',
      'kkkkkkkkkkkk',
    ],
  },
  leimtopf: {
    legend: { k: P.r1, r: P.r3, R: P.r4, g: P.f5, G: P.f7, y: P.f6 },
    rows: [
      '...kkkkkk...',
      '..kRyyyyRk..',
      '..krrrrrrk..',
      '..kRrrrrRk..',
      '..krrrrrrk..',
      '...krrrrk...',
      '.gGggggggGg.',
      'gggyggggyggg',
      '.gggggggggg.',
    ],
  },
  klettenteppich: {
    legend: { m: P.e6, M: P.e7, k: P.e3, g: P.g3, G: P.g4 },
    rows: [
      '..G.....G...',
      '.gGg...gGg..',
      '..g..G..g...',
      '....gGg.....',
      'kkkkkgkkkkkk',
      'kmMmMmMmMmMk',
      'kMmMmMmMmMmk',
      'kkkkkkkkkkkk',
    ],
  },
  knallerbsen: {
    legend: { k: P.e3, b: P.e6, r: P.r3, R: P.r4, w: P.a4, W: P.s9, f: P.f7 },
    rows: [
      '.f....f.....',
      '..f..f......',
      '...ff.......',
      '.rR.wW..rR..',
      '.rr.ww..rr..',
      '....kkkkkk..',
      '.wW.kbbbbk..',
      '.ww.kbrrbk..',
      '....kbbbbk..',
      '....kkkkkk..',
    ],
  },
  oelspur: {
    legend: { n: P.n1, N: P.n3, a: P.a5, b: P.b4, s: P.s5, S: P.s6, r: P.r3 },
    rows: [
      '........ss..',
      '.......sSSs.',
      '.......srrs.',
      '.......sSSs.',
      '.......ssss.',
      '..aNNNNa....',
      '.annnnnnba..',
      'annnNnnnnnb.',
      '.bannnnnaa..',
      '...aabba....',
    ],
  },
  bauplan: {
    legend: { b: P.b2, B: P.b3, w: P.s9, l: P.b5, k: P.n1 },
    rows: [
      '.kkkkkkkkkk.',
      'kBBBBBBBBBBk',
      'kBwwwwBlBBBk',
      'kBwBBwBlBBBk',
      'kBwwwwBllllk',
      'kBBBBBBBBBBk',
      'kBlBlBlBlBBk',
      'kBBBBBBBBBBk',
      '.kkkkkkkkkk.',
      '..kbbbbbbk..',
    ],
  },
};

const cache = new Map();

function build(name) {
  const icon = ICONS[name];
  if (!icon) throw new Error(`Unbekanntes Symbol: ${name}`);
  const h = icon.rows.length;
  const w = Math.max(...icon.rows.map((r) => r.length));
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');
  icon.rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const hex = icon.legend[row[x]];
      if (hex === undefined) continue;
      ctx.fillStyle = hexToCss(hex);
      ctx.fillRect(x, y, 1, 1);
    }
  });
  return canvas;
}

export function iconCanvas(name) {
  if (!cache.has(name)) cache.set(name, build(name));
  return cache.get(name);
}

export function drawIcon(ctx, name, x, y) {
  const c = iconCanvas(name);
  ctx.drawImage(c, Math.round(x), Math.round(y));
  return c;
}

export function iconSize(name) {
  const c = iconCanvas(name);
  return { w: c.width, h: c.height };
}
